{% set name = "dbt-extractor" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt_extractor-{{ version }}.tar.gz
  sha256: 75b1c665699ec0f1ffce1ba3d776f7dfce802156f22e70a7b9c8f0b4d7e80f42

build:
  number: 0
  # maturin isn't availabe on s390x
  skip: true  # [py<36 or s390x or (win and rust_compiler == "rust-gnu")]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('rust') }}
    - maturin
  host:
    - maturin
    - pip
    - python
  run:
    - python

test:
  imports:
    - dbt_extractor
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/dbt-extractor/
  dev_url: https://github.com/dbt-labs/dbt-extractor
  doc_url: https://github.com/dbt-labs/dbt-extractor
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Jinja value templates for dbt model files
  description: |
    It's a tool that processes the most common jinja value templates in dbt model files. 
    The tool depends on tree-sitter and the tree-sitter-jinja2 library.

extra:
  recipe-maintainers:
    - thewchan
