{% set name = "dbt-extractor" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: d6cf08ec793b8bc2bd6e260ef818230ae68a4f71436fa489f08d7db1a52e2ffe

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - maturin >=1.1
    - pip
    - python
  run:
    - python

test:
  imports:
    - dbt_extractor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dbt-extractor
  dev_url: https://github.com/dbt-labs/dbt-extractor
  doc_url: https://github.com/dbt-labs/dbt-extractor
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Jinja value templates for dbt model files
  description: |
    It's a tool that processes the most common jinja value templates in dbt model files. 
    The tool depends on tree-sitter and the tree-sitter-jinja2 library.

extra:
  recipe-maintainers:
    - thewchan
